

# Mutations para a tabela Usuario

# Inserir novo usuário
mutation usuarioInsert($nome: String!) @auth(level: PUBLIC){
  usuario_insert(data: { nome: $nome })
}

# Atualizar usuário existente
mutation usuarioUpsert($usuarioId: UUID, $nome: String) @auth(level: PUBLIC){
  usuario_upsert(data: { usuarioId: $usuarioId,nome: $nome })
}

# Deletar usuário
mutation usuarioDelete($usuarioId: UUID!) @auth(level: PUBLIC){
  usuario_delete(key: { usuarioId: $usuarioId })
}
