
# Query para listar todos os usuários
query listarUsuarios @auth(level: PUBLIC) {
  usuarios {
    usuarioId
    nome
  }
}
# Query para listar todos os usuários
query buscarUsuarioPorId($usuarioId: UUID!) @auth(level: PUBLIC) {
  usuario(key: { usuarioId: $usuarioId }) {
    usuarioId
    nome
  }
}