query ListarUsuarios @auth(level: USER_EMAIL_VERIFIED){
  usuarios {
    id
    nome
  }
}

query ListarFuncoes @auth(level: USER_EMAIL_VERIFIED){
  funcaos{
    funcaoId
    nomeFuncao
  }
}

query BuscarUsuarioPorId ($usuarioId:UUID!) @auth(level: USER_EMAIL_VERIFIED){
  usuario(id:$usuarioId) {
    id
    nome
  }
}

query ListarFuncaoPorId($funcaoId:UUID) @auth(level: USER_EMAIL_VERIFIED){
  funcao(id:$funcaoId){
    funcaoId
    nomeFuncao
  }
}

query ListarPerfisDoUsuario($usuarioId: UUID!) @auth(level: USER_EMAIL_VERIFIED) {
  funcoesUsuario(id: $usuarioId) {
      usuarioId
      funcaoId  
  }
}