"""
Tabela de registro de usuários do sistema
"""
type Usuario @table {
  usuarioId: UUID!
  nome: String!
}

"""
Tabela de registro de funções do sistema
"""
type Funcao @table {
  id: UUID!
  funcaoId: String!
  nomeFuncao: String!
}

"""
Tabela de associação entre usuários e funções
"""
type FuncoesUsuario @table {
  usuarioId: UUID!
  funcaoId: UUID!
}